global:
  resolve_timeout: 5m

route:
  receiver: 'telegram-bot'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'telegram-bot'
    webhook_configs:
      - url: 'http://webhook:5001/alert'
        send_resolved: true