{
 "title": "NGINX Exporter Stats",
 "tags": [
  "nginx",
  "exporter"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nginx_connections_active" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Reading",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "targets": [
    { "expr": "nginx_connections_reading" }
   ]
  },
  {
   "title": "Writing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "targets": [
    { "expr": "nginx_connections_writing" }
   ]
  },
  {
   "title": "Waiting",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "targets": [
    { "expr": "nginx_connections_waiting" }
   ]
  }
 ]
}