name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Check if requirements.txt has changed
        id: check-requirements
        run: |
          git diff --exit-code requirements.txt || echo "requirements.txt changed"
        
      - name: Install dependencies
        if: steps.check-requirements.outputs.changed == 'true'
        run: |
          pip install --upgrade -r requirements.txt

      - name: Run webhook server
        run: |
          nohup python3 webhook/server.py &
          sleep 3

      - name: Run Prometheus check
        run: curl -I http://localhost:9090
